// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obrfxjyeileaxvucpnby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icmZ4anllaWxlYXh2dWNwbmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NDA1ODMsImV4cCI6MjA2NjExNjU4M30.7X7kV96SvBWfrXdM73ftfaLFsdlqOm-1iTfw6lBCcW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);